name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build binary wheel and a source tarball
        run: python setup.py sdist
      - name: Publish package to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
